services:
  speedtest-tracker:
    container_name: speedtest-tracker
    restart: unless-stopped
    ports:
      - 8288:80
    environment:
      - PUID=1000
      - PGID=1000
      - DB_CONNECTION=sqlite
    volumes:
      - /opt/stacks/speedtest-tracker/data:/config
    image: lscr.io/linuxserver/speedtest-tracker:latest
