services:
    web:
        image: daledavies/jump
        ports:
            - 9123:8080
        volumes:
            - /opt/stacks/jump/data:/backgrounds
            - /opt/stacks/jump/data:/favicon
            - /opt/stacks/jump/data:/search
            - /opt/stacks/jump/data:/sites
        environment:
            SITENAME: 'Custom site name'
            OWMAPIKEY: '0a1b2c3d4e5f6a7b8c9d0a1b'
            LATLONG: '51.509865,-0.118092'
