networks:
  bridge:
    driver: bridge
services:
  web:
    image: "xwiki:lts-mariadb-tomcat"
    container_name: xwiki-mariadb-tomcat-web
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      - DB_USER=xwiki
      - DB_PASSWORD=xwiki
      - DB_HOST=xwiki-mariadb-db
    volumes:
      - /opt/stacks/xwiki/data:/usr/local/xwiki
    networks:
      - bridge
  db:
    image: "mariadb:10.5"
    container_name: xwiki-mariadb-db
    volumes:
      - /opt/stacks/xwiki/data:/etc/mysql/conf.d/xwiki.cnf
      - /opt/stacks/xwiki/data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - MYSQL_ROOT_PASSWORD=xwiki
      - MYSQL_USER=xwiki
      - MYSQL_PASSWORD=xwiki
      - MYSQL_DATABASE=xwiki
    networks:
      - bridge
volumes:
  mariadb-data: {}
  xwiki-data: {}
