services:
  letsencrypt:
    image: linuxserver/letsencrypt:latest
    container_name: letsencrypt
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /opt/stacks/letsencrypt/data:/config
    restart: unless-stopped
