services:
  unifivideo:
    image: pducharme/unifi-video-controller:latest
    container_name: unifivideo
    ports:
      - "1935:1935"
      - "7444:7444"
      - "7447:7447"
      - "6666:6666"
      - "7442:7442"
      - "7080:7080"
      - "7443:7443"
      - "7445:7445"
      - "7446:7446"
    volumes:
      - /opt/stacks/unifivideo/data/recordings:/recordings
      - /opt/stacks/unifivideo/data:/config
    restart: unless-stopped
