services:
  flame:
    image: pawelmalak/flame:multiarch
    container_name: flame
    ports:
      - "5005:5005"
    volumes:
      - /opt/stacks/flame/data/app_data:/app/data
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped
