services:
  tooljet-plugins:
    build:
      context: ./
      dockerfile: ./docker/plugins.Dockerfile.dev
    image: tooljet-plugins:development
    platform: linux/x86_64
    volumes:
      - /opt/stacks/tooljet/data:/app/plugins
    command: npm run --prefix plugins start

  tooljet-client:
    build:
      context: ./
      dockerfile: ./docker/client.Dockerfile.dev
    image: tooljet-client:development
    platform: linux/x86_64
    volumes:
      - /opt/stacks/tooljet/data:/app/frontend:delegated
      - /opt/stacks/tooljet/data:/app/plugins
      - /opt/stacks/tooljet/data
    ports:
      - 8082:8082
    environment:
      - WEBPACKER_DEV_SERVER_HOST=0.0.0.0
      - NODE_ENV=development
      - SERVE_CLIENT=false
    command: npm run --prefix frontend start

  tooljet-server:
    build:
      context: ./
      dockerfile: ./docker/server.Dockerfile.dev
    image: tooljet-server:development
    platform: linux/x86_64
    depends_on:
      - tooljet-postgres
    volumes:
      - /opt/stacks/tooljet/data:/app/server:delegated
      - /opt/stacks/tooljet/data:/app/plugins
      - /opt/stacks/tooljet/data
      - /opt/stacks/tooljet/data:/app/.env
      - /opt/stacks/tooljet/data:/app/.env.test
    ports:
      - 3000:3000
    environment:
      - SERVE_CLIENT=false
      - FORCE_COLOR=1
    command: npm run --prefix server start:dev

  tooljet-postgrest:
    image: postgrest/postgrest:v10.1.1.20221215
    ports:
      - "7001:3000"
    env_file:
      - /opt/stacks/tooljet/data
    depends_on:
      - tooljet-postgres

  tooljet-postgres:
    image: postgres:13
    restart: always
    ports:
      - 5432:5432
    volumes:
      - /opt/stacks/tooljet/data:/data/postgres
    environment:
      - POSTGRES_PASSWORD=postgres
