version: "3"

services:

  nitter:
    image: quay.io/unixfox/nitter:latest
    container_name: nitter
    networks:
      - nitter_network
    restart: unless-stopped
    depends_on:
      - redis
    volumes:
      - /opt/stacks/nitter/data:/data
    ports:
      - 3300:8080
    environment:
      - REDIS_HOST="redis"

  redis:
    image: redis:alpine
    container_name: redis
    networks:
      - nitter_network
    restart: unless-stopped
    volumes:
      - /opt/stacks/nitter/data:/data

networks:
  nitter_network:
