volumes:
  firefox:

services:
  firefox:
    image: ghcr.io/linuxserver/firefox
    container_name: firefox
    environment:
      - PUID=1026 #change this to for your settings
      - PGID=100 #change this to for your settings
      - TZ=Europe/Athens  #change this to for your location
    volumes:
      - /opt/stacks/firefox/data:/config
    ports:
      - 3456:3000
    shm_size: "1gb"
    restart: unless-stopped
