services:
  youtubedl-material:
    image: tzahi12345/youtubedl-material:latest
    container_name: youtubedl-material
    ports:
      - "17442:17442"
    volumes:
      - /opt/stacks/youtubedl-material/data/app_appdata:/app/appdata
      - /portainer/Files/AppData/Youtube/Video:/app/video
      - /portainer/Files/AppData/Youtube/Subscriptions:/app/subscriptions
      - /portainer/Files/AppData/Youtube/Users:/app/users
      - /portainer/Files/AppData/Youtube/Audio:/app/audio
    restart: unless-stopped
