services:
  stats:
    image: virtualzone/docker-container-stats
    container_name: docker-stats
    ports:
      - 8383:8080
    environment:
      STATS_UPDATE_INTERVAL: 10
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /opt/stacks/dockercontainerstats/data:/opt/docker-stats/db
