services:
  dokemon:
    image: productiveops/dokemon:latest
    container_name: dokemon
    restart: unless-stopped
    ports:
      - 9090:9090
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /opt/stacks/dokemon/data:/data
