services:
  nginx-proxy-manager-sqlite:
    image: jc21/nginx-proxy-manager:latest
    container_name: nginx-proxy-manager-sqlite
    ports:
      - "80:80"
      - "81:81"
      - "443:443"
    volumes:
      - /opt/stacks/nginx-proxy-manager-sqlite/data:/data
      - /opt/stacks/nginx-proxy-manager-sqlite/data/etc_letsencrypt:/etc/letsencrypt
    restart: unless-stopped
