services:
  logzio-logs-collector:
    image: logzio/docker-collector-logs
    container_name: logzio-logs-collector
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /opt/stacks/logzio-logs-collector/data/lib/docker/containers:/var/lib/docker/containers
    privileged: true
