services:
    actual-server:
        container_name: actual
        ports:
            - 5007:5006
        volumes:
            - /opt/stacks/actual/data:/data
        image: 'actualbudget/actual-server:latest'
        restart: unless-stopped
