services:
  pureftp:
    image: stilliard/pure-ftpd:hardened
    container_name: pureftp
    ports:
      - "21:21"
      - "30000:30000"
      - "30001:30001"
      - "30002:30002"
      - "30003:30003"
      - "30004:30004"
      - "30005:30005"
      - "30006:30006"
      - "30007:30007"
      - "30008:30008"
      - "30009:30009"
    volumes:
      - /opt/mediadepot/apps/pureftp:/etc/pure-ftpd/passwd
      - /media/storage/tvshows:/data/tvshows
      - /media/storage/movies:/data/movies
      - /media/storage/music:/data/music
      - /media/storage/ebooks:/data/ebooks
      - /media/storage/photos:/data/photos
      - /media/storage/documents:/data/documents
      - /media/storage/downloads:/data/downloads
      - /media/storage/software:/data/software
      - /media/temp/blackhole:/data/blackhole
      - /media/temp/processing:/data/processing
    environment:
      - FTP_USER_NAME=depot
      - FTP_USER_HOME=/data
      - FTP_USER_GID=15000
      - FTP_USER_UID=15000
    network_mode: host
