services:
  qflood:
    container_name: qflood
    image: hotio/qflood
    restart: always
    ports:
      - "8282:8080"
      - "3223:3000"
    environment:
      - PUID=1000
      - PGID=1000
      - UMASK=002
      - TZ=Europe/Athens
      - FLOOD_AUTH=false
    volumes:
      - /opt/stacks/flood/data:/config
