services:
  eufy-security-ws:
    image: bropat/eufy-security-ws:latest
    container_name: eufy-security-ws
    ports:
      - "3993:3000"
    volumes:
      - /opt/stacks/eufy-security-ws/data:/data
    restart: unless-stopped
