services:
  snippet-box:
    image: pawelmalak/snippet-box
    container_name: snippet-box
    volumes:
      - /opt/stacks/snippet-box/data:/app/data
    ports:
      - 5000:5000
    restart: unless-stopped
