services:
  kasm:
    image: lscr.io/linuxserver/kasm:latest
    container_name: kasm
    privileged: true
    environment:
      - KASM_PORT=7443
      - DOCKER_MTU=1500 #optional
    volumes:
      - /opt/stacks/kasmworkspaces/data:/opt
      - /opt/stacks/kasmworkspaces/data:/profiles #optional
      - /dev/input:/dev/input #optional
      - /run/udev/data:/run/udev/data #optional
    ports:
      - 63000:3000
      - 7443:443
    restart: unless-stopped
