services:
    fusion:
        ports:
            - 8980:8080
        volumes:
            - /opt/stacks/fusion/data:/data
        environment:
            - PASSWORD=changeme
        image: rook1e404/fusion
