services:
  nzbget:
    image: linuxserver/nzbget:latest
    container_name: nzbget
    ports:
      - "6789:6789"
    volumes:
      - /opt/stacks/nzbget/data:/config
      - /portainer/Downloads:/downloads
    restart: unless-stopped
