services:
  urbackup:
    image: cfstras/urbackup
    container_name: urbackup
    ports:
      - "55413:55413"
      - "55414:55414"
      - "55415:55415"
      - "35622:35622"
    volumes:
      - /opt/stacks/urbackup/data/var_urbackup:/var/urbackup
