services:
  pve-exporter:
    image: prompve/prometheus-pve-exporter
    container_name: pve-exporter
    ports:
      - 9221:9221
    volumes:
      - /opt/stacks/pve-exporter/data:/etc/pve.yml
    restart: always
