services:
  wowza:
    image: sameersbn/wowza:4.1.2-8
    container_name: wowza
    ports:
      - "1935:1935"
      - "8086:8086"
      - "8087:8087"
      - "8088:8088"
    volumes:
      - /opt/stacks/wowza/data/var_lib_wowza:/var/lib/wowza
