services:
  vsftpd:
    image: delfer/alpine-ftp-server
    container_name: vsftpd
    ports:
      - "21:21"
      - "21000:21000"
      - "21001:21001"
      - "21002:21002"
      - "21003:21003"
      - "21004:21004"
      - "21005:21005"
      - "21006:21006"
      - "21007:21007"
      - "21008:21008"
      - "21009:21009"
      - "21010:21010"
    volumes:
      - /media/storage/tvshows:/home/depot/tvshows
      - /media/storage/movies:/home/depot/movies
      - /media/storage/music:/home/depot/music
      - /media/storage/ebooks:/home/depot/ebooks
      - /media/storage/photos:/home/depot/photos
      - /media/storage/documents:/home/depot/documents
      - /media/storage/downloads:/home/depot/downloads
      - /media/storage/software:/home/depot/software
      - /media/temp/blackhole:/home/depot/blackhole
      - /media/temp/processing:/home/depot/processing
    network_mode: host
