services:
  hydra2:
    image: linuxserver/hydra2:latest
    container_name: hydra2
    ports:
      - "5076:5076"
    volumes:
      - /opt/stacks/hydra2/data/config:/config
      - /opt/stacks/hydra2/data/downloads:/downloads
