services:
  transmission-openvpn:
    image: haugene/transmission-openvpn:3.7.1
    container_name: transmission-openvpn
    ports:
      - "9091:9091"
    volumes:
      - /opt/stacks/transmission-openvpn/data:/config
      - /portainer/Downloads:/data
      - /etc/localtime:/etc/localtime
    restart: unless-stopped
    privileged: true
