services:
  thelounge:
    image: linuxserver/thelounge:latest
    container_name: thelounge
    ports:
      - "9000:9000"
    volumes:
      - /opt/stacks/thelounge/data:/config
    restart: unless-stopped
