services:
  sickgear:
    image: linuxserver/sickgear:latest
    container_name: sickgear
    ports:
      - "8081:8081"
    volumes:
      - /opt/stacks/sickgear/data:/config
      - /portainer/TV:/tv
      - /portainer/Downloads:/downloads
    restart: unless-stopped
