services:
  magento2:
    image: alankent/gsd:latest
    container_name: magento2
    ports:
      - "80:80"
      - "3000:3000"
      - "3001:3001"
    volumes:
      - /opt/stacks/magento2/data/var_www_html:/var/www/html/
