services:
  protonmail-bridge:
    image: shenxn/protonmail-bridge:latest
    container_name: protonmail-bridge
    ports:
      - "143:143"
      - "25:25"
    volumes:
      - /portainer/Files/AppData/ProtonMail-Bridge:/root
    restart: unless-stopped
