services:
  shaarli:
    container_name: Shaarli
    image: ghcr.io/shaarli/shaarli:latest
    restart: on-failure
    ports:
      - 7755:80
    volumes:
      - /opt/stacks/shaarli/data:/var/www/shaarli/cache:rw
      - /opt/stacks/shaarli/data:/var/www/shaarli/data:rw
    environment:
      PUID: 1026
      PGID: 100
      TZ: Europe/Athens
