services:
  broadlinkmanager:
    image: techblog/broadlinkmanager
    network_mode: host
    container_name: broadlinkmanager
    restart: unless-stopped
    volumes:
      - /opt/stacks/broadlink-manager/data:/opt/broadlinkmanager/data

