services:
  homer:
    image: b4bz/homer:latest
    container_name: homer
    ports:
      - "8902:8080"
    volumes:
      - /opt/stacks/homer/data/www_assets:/www/assets
      - /opt/stacks/homer/data/www_config.yml:/www/config.yml
    restart: unless-stopped
