services:
  endlessh:
    image: linuxserver/endlessh:latest
    container_name: endlessh
    ports:
      - "22:2222"
    volumes:
      - /volume1/docker/endlessh/config:/config
    restart: unless-stopped
