services:
  openvpn-as:
    image: linuxserver/openvpn-as:latest
    container_name: openvpn-as
    ports:
      - "943:943"
      - "9443:9443"
      - "1194:1194"
    volumes:
      - /opt/stacks/openvpn-as/data/config:/config
