services:
  logzio-metrics-collector:
    image: logzio/docker-collector-metrics
    container_name: logzio-metrics-collector
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /sys/fs/cgroup:/hostfs/sys/fs/cgroup:ro
      - /proc:/hostfs/proc:ro
      - /:/hostfs:ro
    privileged: true
