services:
    #FPM image
    koillection:
        container_name: koillection
        image: koillection/koillection:dev
        restart: always
        ports:
            - 181:80
        environment:
            - APP_ENV=dev
            - APP_DEBUG=1
            - DB_DRIVER=pdo_pgsql
            - DB_NAME=koillection
            - DB_HOST=postgresql
            - DB_PORT=25432
            - DB_USER=postgres
            - DB_PASSWORD=password
            - DB_VERSION=14
            - PHP_TZ=Europe/Athens
            - HTTPS_ENABLED=0
        depends_on:
            - koinmysql
            - postgresql
        volumes:
            - /opt/stacks/koillection/data:/var/www/koillection/public/uploads
            - /opt/stacks/koillection/data:/var/www/koillection

    postgresql:
        container_name: postgresql
        image: postgres:14
        environment:
            - POSTGRES_DB=koillection
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=password
            - POSTGRES_HOST_AUTH_METHOD=trust
        ports:
            - 25432:5432
        volumes:
            - /opt/stacks/koillection/data:/var/lib/postgresql/data

    koinmysql:
        container_name: mysql
        image: mysql:latest
        command: --default-authentication-plugin=mysql_native_password
        environment:
            - MYSQL_ROOT_PASSWORD=password
            - MYSQL_DATABASE=koillection
        ports:
            - 43306:3306
        volumes:
            - /opt/stacks/koillection/data:/var/lib/mysql
