services:
  searxng:
    image: searxng/searxng:latest
    container_name: searxng
    ports:
      - "9017:8080"
    volumes:
      - /opt/stacks/searxng/data/etc_searxng:/etc/searxng
    restart: unless-stopped
