services:
  dokuwiki:
    image: linuxserver/dokuwiki:latest
    container_name: dokuwiki
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /volume1/docker/dokuwiki/config:/config
    restart: unless-stopped
