services:

  midarr:
    container_name: midarr
    build: .
    ports:
      - 4000:4000
    volumes:
      - /opt/stacks/midarr/data:/app
      - /opt/stacks/midarr/data:/movies
      - /opt/stacks/midarr/data:/series
    environment:
      - APP_URL=http://midarr:4000
      - SETUP_ADMIN_EMAIL=admin@email.com
      - SETUP_ADMIN_NAME=admin
      - SETUP_ADMIN_PASSWORD=passwordpassword
      - RADARR_BASE_URL=http://radarr:7878
      - RADARR_API_KEY=d031e8c9b9df4b2fab311d1c3b3fa2c5
      - SONARR_BASE_URL=http://sonarr:8989
      - SONARR_API_KEY=1accda4476394bfcaddefe8c4fd77d4a
    command: bash -c "chmod u+x misc/entry-point-local.sh && ./misc/entry-point-local.sh"
