services:
  libreddit:
    image: libreddit/libreddit:armv7
    container_name: libreddit
    ports:
      - "8088:8080"
    volumes:
      - /opt/stacks/libreddit/data:/config
    restart: unless-stopped
