services:
  syslog-ng:
    image: linuxserver/syslog-ng:latest
    container_name: syslog-ng
    ports:
      - "514:5514"
      - "601:6601"
      - "6514:6514"
    volumes:
      - /volume1/docker/syslog-ng/config:/config
      - /var/log:/var/log
    restart: unless-stopped
