services:
  yacht:
    image: selfhostedpro/yacht:latest
    container_name: yacht
    ports:
      - "8001:8000"
    volumes:
      - yacht:/config
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped
