services:
  trilium:
    image: zadam/trilium:latest
    container_name: trilium
    ports:
      - "3388:8080"
    volumes:
      - /opt/stacks/trilium/data/home_node_trilium-data:/home/node/trilium-data
    restart: unless-stopped
