services:
  airsonic:
    image: lscr.io/linuxserver/airsonic
    container_name: airsonic
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Athens
    volumes:
      - /opt/stacks/airsonic/data:/config
      - /opt/stacks/airsonic/data:/music
      - /opt/stacks/airsonic/data:/playlists
      - /opt/stacks/airsonic/data:/podcasts
      - /opt/stacks/airsonic/data:/media #optional
    ports:
      - 4040:4040
    restart: unless-stopped
