services:
  transmission-openvpn-latest:
    image: haugene/transmission-openvpn:latest
    container_name: transmission-openvpn-latest
    ports:
      - "9091:9091"
    volumes:
      - /opt/stacks/transmission-openvpn-latest/data:/config
      - /portainer/Downloads:/data
      - /etc/localtime:/etc/localtime
    restart: unless-stopped
    privileged: true
