services:
  db:
    image: mariadb
    command: --max-allowed-packet=64MB
    restart: always
    volumes:
      - /opt/stacks/matomo/data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=enterYOURpwd
    # env_file:
    #  - ./db.env

  app:
    image: matomo
    restart: always
    volumes:
      - /opt/stacks/matomo/data:/var/www/html/config
      - /opt/stacks/matomo/data:/var/www/html/logs
      - matomo:/var/www/html
    environment:
      - MATOMO_DATABASE_HOST=db
    # env_file:
    #   - ./db.env
    ports:
      - 8282:80 #changed from default 8080

volumes:
  db:
  matomo:
