services:
  terraria-server:
    image: passivelemon/terraria-docker:latest
    container_name: terraria-server
    ports:
      - "7777:7777"
    volumes:
      - /portainer/Files/AppData/Libraries/StirlingPDF/tessdata:/usr/share/tesseract-ocr/5/tessdata
    restart: unless-stopped
