services:
  filebrowser-latest:
    image: filebrowser/filebrowser:latest
    container_name: filebrowser-latest
    ports:
      - "8082:80"
    volumes:
      - /portainer/Downloads:/srv
      - /opt/stacks/filebrowser-latest/data/database_filebrowser.db:/database/filebrowser.db
      - /opt/stacks/filebrowser-latest/data/config_settings.json:/config/settings.json
    restart: unless-stopped
