services:
    jellyseerr:
       image: fallenbagel/jellyseerr:latest
       container_name: jellyseerr
       environment:
            - LOG_LEVEL=INFO
            - TZ=Europe/Athens
       ports:
            - 5055:5055
       volumes:
            - /opt/stacks/jellyseer/data:/app/config
       restart: unless-stopped
