services:
    gathio:
        build: .
        links:
            - mongo
        ports:
            - 3022:3000
    mongo:
        image: mongo:latest
        volumes:
             - /opt/stacks/gathio/data:/data/db
