services:
  homepage:
    image: ghcr.io/benphelps/homepage:latest
    container_name: homepage
    ports:
      - 6006:3000
    volumes:
      - /opt/stacks/homepage/data:/app/config
      - /var/run/docker.sock:/var/run/docker.sock
