services:
  filezilla:
    image: linuxserver/filezilla:latest
    container_name: filezilla
    ports:
      - "3000:3000"
    volumes:
      - /volume1/docker/filezilla/config:/config
    restart: unless-stopped
