services:
  nexterm:
    ports:
      - "6989:6989"
    restart: always
    volumes:
      - /opt/stacks/nexterm/data:/app/data
    image: germannewsmaker/nexterm:1.0.2-OPEN-PREVIEW
volumes:
  nexterm:
