services:
  pihole:
    image: pihole/pihole:latest
    container_name: pihole
    ports:
      - "53:53"
      - "53:53"
      - "67:67"
      - "1010:80"
      - "4443:443"
    volumes:
      - /opt/stacks/pihole/data/etc_pihole:/etc/pihole
      - /opt/stacks/pihole/data/etc_dnsmasq.d:/etc/dnsmasq.d
    restart: unless-stopped
